### ISSUE TITLE
Categorized Functions for Units

### ISSUE THREAD

**Issue by Schneufelbruder** [mkvph0ch/galle#15]
usage of structs, methods, interfaces (object-oriented like programming)

**Comment by mkvph0ch** [comment]
an example of structs, methods, interfaces can be found in struct/main.go
Example https://gobyexample.com/interfaces https://medium.com/rungo/structures-in-go-76377cc106a2
Set Defaults in Struct https://www.geeksforgeeks.org/how-to-assign-default-value-for-struct-field-in-golang/

**Comment by Schneufelbruder** [comment]
Merged  with #17 to #19
