### ISSUE TITLE
Output with recap

### ISSUE THREAD

**Issue by Schneufelbruder** [mkvph0ch/galle#17]
Sentence like: 300 K is converted to 0.025851999786435 eV.
Thank you for choosing our services. Can we otherwise be of service?

**Comment by mkvph0ch** [comment]
I think this can be easily achieved with struct objects and a separate function, e.g.

func(x PhysUnit) {
   X.value x.unit was converted to ...
}

**Comment by mkvph0ch** [comment]
added for kelvin only, further implementation needed

**Comment by Schneufelbruder** [comment]
Merged with #15 to #19
