### ISSUE TITLE
save output as .txt file

### ISSUE THREAD

**Issue by Schneufelbruder** [mkvph0ch/galle#22]

**Comment by mkvph0ch** [comment]
I suggest the ouput to be, e.g.

T [K], T [°C]
298.15, 25
273.15, 0

in general

y1.id [y1.unit], y2.id [y2.unit]
y1.value[0], y2.value[0]
y1.value[1], y2.value[1]

use for loop with index i?

Literature
https://golang.org/pkg/encoding/csv/
https://medium.com/@barunthapa/working-with-csv-in-go-50a4f540e623

**Comment by mkvph0ch** [comment]
done
