### ISSUE TITLE
Add energy conversion

### ISSUE THREAD

**Issue by Schneufelbruder** [mkvph0ch/galle#4]
room temperature = 25 meV

**Comment by mkvph0ch** [comment]
https://en.wikipedia.org/wiki/Electronvolt#Temperature

1 eV = 1.602 177 33 × 10-19 J = 11 604.45 K. Thus, 1 eV is approximately equal to 104 K, or 1 K approximately equal to 10-4 eV.

**Comment by Schneufelbruder** [comment]
Added K to eV, need to add eV->K

**Comment by Schneufelbruder** [comment]
K to eV added. Issue closed.
