### ISSUE TITLE
Project Meeting #3

### ISSUE THREAD

**Issue by Schneufelbruder** [mkvph0ch/galle#8]
Saturday (01/08/20) or Sunday (02/08/20) @mkvph0ch ?

- [x] New Issues

- [x] Close  #2 

- [x] Code Improvements

- [x] Project Management / Planning (bi-weekly meetings?)

- [x] Other

**Comment by mkvph0ch** [comment]
Sunday (02/08/20)

**Comment by mkvph0ch** [comment]
- [x] remove obsolete code
- [x] summarize wavelength<->wavenumber functions
- [x] split code, e.g. main.go (input/output) and functions.go (conversion functions)
- [x] usage of structs, methods, interfaces (object-oriented like programming)
- [x] handling of errors, e.g. division by 0
- [x] multiple inputs/outputs
`func wave(nums ...float64) []float64 { 
	var result []float64 
	for _, v := range nums {
		result = append(result, 1/(v*math.Pow10(-7)))
	}
	return result
  }`
- [x] command line interface (should be probably delayed)

**Comment by Schneufelbruder** [comment]
Existing Code Improvements

- [ ] Split functions and main.go (functions.go, etc.)
