### ISSUE TITLE
Split functions and main.go

### ISSUE THREAD

**Issue by mkvph0ch** [mkvph0ch/galle#9]
Split the functions into a separate .go file and import it to main.go

**Comment by mkvph0ch** [comment]
importing packages in golang
https://riptutorial.com/go/example/22421/importing-packages

**Comment by Schneufelbruder** [comment]
Add automatic converter adder function
So that new conversions are saved in external function-file

**Comment by mkvph0ch** [comment]
https://golang.org/doc/tutorial/create-module

**Comment by mkvph0ch** [comment]
done
used this tutorial https://golangbot.com/go-packages/
